
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING'
export const GET_POSTS_OK = 'GET_POSTS_OK'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

export const DELETE_POST_PENDING = 'DELETE_POST_PENDING'
export const DELETE_POST_OK = 'DELETE_POST_OK'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'

export const GET_POST_EDIT= 'GET_POST_EDIT'
export const EDIT_POST_PENDING = 'EDIT_POST_PENDING'
export const EDIT_POST_OK = 'EDIT_POST_OK'
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR'

